[package]
name = "gcs_proxy"
version = "0.1.0"
authors = ["norinorin <norizontunes@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = { version = "3", features = ["openssl"] }
clap = "2.33"
url = "2.0"
openssl = { version = "0.10", features = ["vendored"] }
env_logger = "0.8"